# Purdue GenAI Studio Assistant Configuration
# This file configures the AI assistant for different courses

# Course Information
course:
  name: "STAT 350"  # e.g., "STAT 350", "CS 180", "MA 261"
  department: "Department of Statistics"
  college: "College of Science"
  
# Assistant Settings
assistant:
  name: "STAT 350 Assistant"  # Name shown in chat
  title: "STAT 350 Course Assistant"  # Title in header
  welcome_message: "I'm here to help you with probability concepts, distributions, and statistical theory. Ask me anything about your STAT 350 coursework!"
  input_placeholder: "Ask a question about STAT 350..."

# GenAI Studio Settings
genai:
  base_url: "https://genai.rcac.purdue.edu"
  model: "gpt-stat350"  # Model from GenAI Studio collection
  temperature: 0.7
  timeout: 60
  stream_timeout: 120
  max_tokens: 2000
  
# UI Customization
ui:
  logo_file: "lattice_ai_icon.png"  # Logo file in static directory
  footer_text: "Purdue University • Department of Statistics • STAT 350"
  
# File Upload Settings
file_upload:
  enabled: true
  max_size_mb: 10
  allowed_extensions:
    - .txt
    - .pdf
    - .csv
    - .xlsx
    - .json
    - .py
    - .cpp
    - .java
    - .md
    - .r
    - .ipynb
    
# Features
features:
  latex_rendering: true
  markdown_support: true
  code_highlighting: true
  file_analysis: true
  source_citations: true  # Add "Source:" line for gpt-stat350
  
# Security & Production Settings
security:
  rate_limit:
    enabled: true
    requests_per_minute: 30
    requests_per_hour: 500
  cors:
    enabled: true
    allowed_origins:
      - "https://genai.purdue.edu"
      - "https://*.purdue.edu"
  session:
    timeout_minutes: 120
    
# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/assistant.log"
  max_size_mb: 100
  backup_count: 5
  
# Advanced Settings
advanced:
  memory_per_conversation: 50  # Max messages to keep in context
  streaming_buffer_size: 5
  health_check_interval: 300  # seconds
  
# Model-Specific Settings
model_settings:
  gpt-stat350:
    add_source_instruction: true
    source_instruction: "\n\nPlease include a Source line at the end of your response."
  default:
    add_source_instruction: false